apiVersion: v1
kind: Service
metadata:
  name: spark-worker
  namespace: spark
spec:
  type: NodePort               
  selector:
    app: spark
    role: worker
  ports:
    - name: spark-worker-ui
      port: 8081                
      targetPort: 8081          
      nodePort: 30801     